name: HealthChat Release to Google Play Store

on:
  workflow_dispatch:
    inputs:
      track:
        description: 'Play Store track to upload to'
        required: true
        default: 'internal'
        type: choice
        options:
          - internal
          - alpha
          - beta
          - production
      release-status:
        description: 'Release Status App'
        required: true
        default: 'completed'
        type: choice
        options:
          - completed
          - inProgress
          - halted
          - draft

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx6g -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g" -Dkotlin.incremental=false -XX:+UseG1GC
  CI_GRADLE_ARG_PROPERTIES: --stacktrace -PpreDexEnable=false --max-workers 2 --no-daemon

jobs:
  release:
    name: Build and upload AAB to Play Store
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release/healthchat'
    steps:
      - uses: actions/checkout@v4

      - name: Use JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > vector-app/signature/release.keystore

      - name: Decode google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > vector-app/src/gplay/release/google-services.json

      - name: Build Release AAB
        run: |
          ./gradlew bundleGplayRelease $CI_GRADLE_ARG_PROPERTIES
        env:
          RELEASE_STORE_FILE: signature/release.keystore
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: healthchat-release-aab
          path: vector-app/build/outputs/bundle/gplayRelease/*.aab

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: ch.healthchat.element
          releaseFiles: vector-app/build/outputs/bundle/gplayRelease/*.aab
          track: ${{ inputs.track }}
          status:  ${{ inputs.release-status }}
          changesNotSentForReview: true
